sudo: false
language: node_js
node_js:
- stable
before_script:
- npm install -g bower grunt-cli
- bower install
- gem install compass
before_deploy:
- grunt build
deploy:
  provider: heroku
  buildpack: ruby
  skip_cleanup: true
  api_key:
    secure: kcf+gsp+TV6ZUFsHc8R6/ZeAKdyOj3UCbmt+hwMAkgeYwjSJHRHm1M/FO08CESZIMBA2L//HjVpEpZwdVbBydNijgzmbwg+yWYtCYa8vF4IxcHp0S700f8Lz3Xu4uN4/6iaOTkdaBmRIOY0GEx0yCMXqjplwUYhq8v9/sfYreiP0ux+t1+qFgSIoGG7oiieA905Q4lAYSxbG2bpF3ruJKaiED/jQXFyesQXUXFPj3UwCji5quHQ79hDV7qVReCNejg7HqBW6psKtDCOG8EdjIgDaxagLoe99K+i1/vSHK/8WRejs4PHoXYF3V2aFO9/TTAWEdjWfDXVN/vZfei+lmOJKRtxYTUqeyvLbwDyq585k4AE/Xz28eJt+9eGjRpKmy6VvTOed8iolfqDGrjEz0pgqrAGdtLKpLbyY3hjRGPcy7XdqV915E9Q1/h9gqcPGrOoiisLfC8Ietuw/abd8rLChD9C5WyBMUMRvxRJZHTssmKZ1Zv+Cxjc9bLQNDPeVCOi0fTtb9zEIYnOxLfCM/oQRhZneZ5FG2G0yPxmI5syK2Gl/OrgMny3BJrf00KncjlyIv5u8OJJvdw5zebwyAMtf96GmPTOm4vMtMTLcU8MuBU2ejZb3JDAnRwZi1JBzkkniJ2/dPiEOpg85MHi1HFnjL8+HwxLh+Q83y+xTZ9U=
  app: rssreader-client-staging
  on:
    branch: master
    repo: PerceptumNL/eduraam-rssreader-frontend
